[package]
name = "chat_no_db"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"


[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
